// Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//   This code was generated by a tool.
//     Hazelcast Client Protocol Code Generator
//     https://github.com/hazelcast/hazelcast-client-protocol
//   Change to this file will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable IDE0051 // Remove unused private members
// ReSharper disable UnusedMember.Local
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Hazelcast.Protocol.BuiltInCodecs;
using Hazelcast.Protocol.CustomCodecs;
using Hazelcast.Core;
using Hazelcast.Messaging;
using Hazelcast.Logging;
using Hazelcast.Clustering;
using Hazelcast.Serialization;
using Microsoft.Extensions.Logging;

namespace Hazelcast.Protocol.Codecs
{
    /// <summary>
    /// Registers a new CP group availability listener.
    ///</summary>
#if SERVER_CODEC
    internal static class CPSubsystemAddGroupAvailabilityListenerServerCodec
#else
    internal static class CPSubsystemAddGroupAvailabilityListenerCodec
#endif
    {
        public const int RequestMessageType = 2228992; // 0x220300
        public const int ResponseMessageType = 2228993; // 0x220301
        private const int RequestLocalFieldOffset = Messaging.FrameFields.Offset.PartitionId + BytesExtensions.SizeOfInt;
        private const int RequestInitialFrameSize = RequestLocalFieldOffset + BytesExtensions.SizeOfBool;
        private const int ResponseResponseFieldOffset = Messaging.FrameFields.Offset.ResponseBackupAcks + BytesExtensions.SizeOfByte;
        private const int ResponseInitialFrameSize = ResponseResponseFieldOffset + BytesExtensions.SizeOfGuid;
        private const int EventGroupAvailabilityEventInitialFrameSize = Messaging.FrameFields.Offset.PartitionId + BytesExtensions.SizeOfInt;
        private const int EventGroupAvailabilityEventMessageType = 2228994; // 0x220302

#if SERVER_CODEC
        public sealed class RequestParameters
        {

            /// <summary>
            /// Denotes whether register a local listener or not.
            ///</summary>
            public bool Local { get; set; }
        }
#endif

        public static ClientMessage EncodeRequest(bool local)
        {
            var clientMessage = new ClientMessage
            {
                IsRetryable = false,
                OperationName = "CPSubsystem.AddGroupAvailabilityListener"
            };
            var initialFrame = new Frame(new byte[RequestInitialFrameSize], (FrameFlags) ClientMessageFlags.Unfragmented);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.MessageType, RequestMessageType);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.PartitionId, -1);
            initialFrame.Bytes.WriteBoolL(RequestLocalFieldOffset, local);
            clientMessage.Append(initialFrame);
            return clientMessage;
        }

#if SERVER_CODEC
        public static RequestParameters DecodeRequest(ClientMessage clientMessage)
        {
            using var iterator = clientMessage.GetEnumerator();
            var request = new RequestParameters();
            var initialFrame = iterator.Take();
            request.Local = initialFrame.Bytes.ReadBoolL(RequestLocalFieldOffset);
            return request;
        }
#endif

        public sealed class ResponseParameters
        {

            /// <summary>
            /// Registration id for the listener.
            ///</summary>
            public Guid Response { get; set; }
        }

#if SERVER_CODEC
        public static ClientMessage EncodeResponse(Guid response)
        {
            var clientMessage = new ClientMessage();
            var initialFrame = new Frame(new byte[ResponseInitialFrameSize], (FrameFlags) ClientMessageFlags.Unfragmented);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.MessageType, ResponseMessageType);
            initialFrame.Bytes.WriteGuidL(ResponseResponseFieldOffset, response);
            clientMessage.Append(initialFrame);
            return clientMessage;
        }
#endif

        public static ResponseParameters DecodeResponse(ClientMessage clientMessage)
        {
            using var iterator = clientMessage.GetEnumerator();
            var response = new ResponseParameters();
            var initialFrame = iterator.Take();
            response.Response = initialFrame.Bytes.ReadGuidL(ResponseResponseFieldOffset);
            return response;
        }

#if SERVER_CODEC
        public static ClientMessage EncodeGroupAvailabilityEventEvent(Hazelcast.CP.RaftGroupId groupId, ICollection<Hazelcast.CP.ICPMember> members, ICollection<Hazelcast.CP.ICPMember> unavailableMembers)
        {
            var clientMessage = new ClientMessage();
            var initialFrame = new Frame(new byte[EventGroupAvailabilityEventInitialFrameSize], (FrameFlags) ClientMessageFlags.Unfragmented);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.MessageType, EventGroupAvailabilityEventMessageType);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.PartitionId, -1);
            clientMessage.Append(initialFrame);
            clientMessage.Flags |= ClientMessageFlags.Event;
            RaftGroupIdCodec.Encode(clientMessage, groupId);
            ListMultiFrameCodec.Encode(clientMessage, members, CPMemberCodec.Encode);
            ListMultiFrameCodec.Encode(clientMessage, unavailableMembers, CPMemberCodec.Encode);
            return clientMessage;
        }
#endif
        public static ValueTask HandleEventAsync(ClientMessage clientMessage, HandleGroupAvailabilityEventEventAsync handleGroupAvailabilityEventEventAsync, ILoggerFactory loggerFactory)
        {
            using var iterator = clientMessage.GetEnumerator();
            var messageType = clientMessage.MessageType;
            if (messageType == EventGroupAvailabilityEventMessageType)
            {
                iterator.Take(); // empty initial frame
                var groupId = RaftGroupIdCodec.Decode(iterator);
                var members = ListMultiFrameCodec.Decode(iterator, CPMemberCodec.Decode);
                var unavailableMembers = ListMultiFrameCodec.Decode(iterator, CPMemberCodec.Decode);
                return handleGroupAvailabilityEventEventAsync(groupId, members, unavailableMembers);
            }
            loggerFactory.CreateLogger(typeof(EventHandler)).LogDebug("Unknown message type received on event handler :" + messageType);
            return default;
        }

        public delegate ValueTask HandleGroupAvailabilityEventEventAsync(Hazelcast.CP.RaftGroupId groupId, IList<Hazelcast.CP.CPMemberInfo> members, IList<Hazelcast.CP.CPMemberInfo> unavailableMembers);
    }
}